### PR TITLE
zh-CN: fix some translations

### PR DESCRIPTION
**Pull request by ghost**
1. Add whitespaces between ASCII and Chinese characters.
2. We don't say "客制化" in the mainland of China but "定制化".
3. Make some English meaning more clearly because we don't translate
them so directly, we should let more Chinese know what they really mean.
4. Make translations more easy and clear to understand.

### CODE REVIEW

**Comment by ghost** [comment]
@princemaple: I find there're some translations not fitting the local mainland Chinese people's expression, with some translation errors, here's the fix, plz check, thanks!

**Comment by princemaple** [comment]
I don't mind most of them. GIF is still better though. Chinese tend to spell them out one character a time. Having them as lowercase like a word doesn't make sense.

**Comment by ghost** [comment]
> I don't mind most of them. GIF is still better though. Chinese tend to spell them out one character a time. Having them as lowercase like a word doesn't make sense.

OK, I've fixed all of them by saying "GIF 动画", it makes more clear with a full meaning ;)

**Review by princemaple — APPROVED** [review]
As long as the newly added spaces don't have a negative impact on page layout, they are good to go in.

**Comment by ghost** [comment]
> As long as the newly added spaces don't have a negative impact on page layout, they are good to go in.

Yes, I've tested locally and everything goes fine with me ;)

**Comment by NickeManarin** [comment]
Thanks!

**Comment by ghost** [comment]
@NickeManarin : Pleasure.

**Pull request merged**
